# Merges Main to Stage to Keep Stage up-to-date with Production

name: Merge Main to Stage

on:
  workflow_run:
    workflows: ["main"]
    branches: [main]
    types: 
      - completed
      - requested
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> stage
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: stage
          github_token: ${{ github.token }}
